name: Build and Release Installer

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # Nécessaire pour générer un .exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # Version la plus récente en 2025

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==6.0.0 requests  # Version de PyInstaller compatible avec Python 3.12

      - name: Build installer with PyInstaller
        run: |
          cd installer
          pyinstaller --onefile --windowed --icon=NONE main.py
          mv dist/main.exe ../installer.exe  # Déplace le .exe à la racine

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}  # Numéro de build comme version
          name: CDIGraph Installer v${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            installer.exe
            installer/main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
